INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9780141039411,'Spirituality','A New Earth','','Eckhart Tolle','We get so caught up in the minutiae of everyday life, worrying about things we have no control over. This book helps you take a look at what you can do to change your attitude toward this. It reminds you to stay in the moment and not allow your ego to take over. I would highly recommend it to anyone doing some soul searching or spiritual learning.','Paperback','English','1st edition','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (8194790883,'Self Help','Think And Grow Rich','','Napoleon Hill ','Ever wondered how life would be if we could condition our minds to Think and Grow Rich?
Author Napoleon Hill claims to have based this book on twenty years of rigorous research on the lives of those who had amassed great wealth and made a fortune. Observing their habits, their ways of working and the principles they followed, Hill put together laws and philosophies that can be practiced in everyday life to achieve all-round success.','Paperback','English','2nd edition','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (8172345666,'Self Help','The Power of Your Subconscious Mind','','Joseph Murphy','This remarkable book by Dr. Joseph Murphy, one of the pioneering voices of affirmative thinking, will unlock for you the truly staggering powers of your subconscious mind. Combining time-honored spiritual wisdom with cutting edge scientific research, Dr. Murphy explains how the subconscious mind influences every single thing that you do and how, by understanding it and learning to control its incredible force, you can improve the quality of your daily life.','Paperback','English','1st edition','Y','Reference books','Lent');
INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9788126552566,'Education','Principals of Physics','','Robert Resnick Jearl Walker, David Halliday ','','','English','10th Edition','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (1612680194,'Personal Finance','Rich Dad Poor Dad','',' Robert T. Kiyosaki','It has been nearly 25 years since Robert Kiyosaki’s Rich Dad Poor Dad first made waves in the Personal Finance arena.
It has since become the #1 Personal Finance book of all time... translated into dozens of languages and sold around the world.','Paperback','English','42836','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (1788162056,'Self Help','Stillness Is The Key','','Ryan Holiday','Filled with wisdom and examples from historical and contemporary figures, this book shows how to cultivate this quality in your own life. Because stillness is not merely inactivity, but the doorway to the self-mastery, discipline and focus necessary to succeed in this competitive, noisy world.','Hard Cover','English','43780','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (8190453017,'Self Help','Stay Hungry Stay Foolish','','Rashmi Bansal ','Alice Bhatti has just come out of prison and is looking for a second chance. Sheas hungry, tough, and full of fight, but being a Catholic choohra in Karachi means she also needs good luck. A lot of it. Aliceas prayers are answered when she gets a job as junior nurse at the Sacred Heart Hospital, a squalid public hospital full of shoot-out victims and homeless drug addicts. There she meets Teddy Butt, a trigger happy, ex-body builder and a part- time goon for the police. ','Paperback','English','39783','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (8190453018,'Numerology','Numerology For Everybody','','Montrose','A book on Kabalah Numerology method','Paperback','English','24959','N','Reference books','Acquire');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (241257549,'Psychology','Lateral Thinking','','Edward de Bono','THE classic work about improving creativity from world-renowned writer and philosopher Edward de Bono In schools we are taught to meet problems head-on: what Edward de Bono calls vertical thinking. This works well in simple situations - but we are at a loss when this approach fails. What then? Lateral thinking is all about freeing up your imagination. ','Paperback','English','42668','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (99590085,'Civilisation & Culture','Sapiens: A Brief History of Humankind','','Yuval Noah Harari ','Earth is 4.5 billion years old. In just a fraction of that time, one species among countless others has conquered it: us.
In this bold and provocative book, Yuval Noah Harari explores who we are, how we got here and where we are going.','Paperback','English','42166','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (99536013,'Novel','Catch-22','','Joseph Heller ','Discover Joseph Hellers hilarious and tragic satire on military madness, and the tale of one mans efforts to survive it.','Paperback','English','34627','Y','Reference books','Lent');
INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (718170024,'Novel','Hotel','','Arthur Hailey','The #1 New York Times–bestselling author of Airport reveals the inner workings of a New Orleans hotel—and the human drama unfolding behind its closed doors.','Hard Cover','English','41772','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9388144295,'Fiction','The Odyssey','','Holmer','An exquisitely designed leather-bound edition with a gold-foiled cover, this omnibus featuring Samuel Butler’s translations of the two Homeric epics comes with a ribbon bookmark, gilded edges and beautiful endpapers. Ideal to be read and treasured, it makes for a perfect addition to any library.','Hard Cover','English','43313','Y','Reference books','Lent');
INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9387779343,'Drama','Hamlet','','William Shakespeare','What happens when Hamlet, the Prince of Denmark, encounters his father’s ghost which reveals to him the secrets of his father’s murder, laying upon him the duty of revenge? Unconvinced and indecisive, Hamlet—the Prince of Demark, re-enacts the murder to find the truth. Will he be able to unmask and avenge the brutal and cold-blooded murder of his father? Will his inner struggle between taking a revenge and his propensity to delay thwart his desires to act?','Paperback','English','43191','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (143063928,'Management','The Case of the Bonsai Manager','',' R. Gopalakrishnan','The Case of the Bonsai Manager is the perfect antidote for every manager who feels they are not achieving their full potential. Effective leadership is not just about hard facts but also about listening to, and using, your intuition.','Paperback','English','40031','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9781400077427,'Psychology','Stumbling On Happiness','','Daniel Gilbert','Bringing to life scientific research in psychology, cognitive neuroscience, philosophy, and behavioral economics, this bestselling book reveals what scientists have discovered about the uniquely human ability to imagine the future, and about our capacity to predict how much we will like it when we get there. ','Paperback','English','2-=Mar-07','Y','Reference books','Lent');
INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (743468597,'Self Help','First Thing First','',' R. Stephen Covey ','FIRST THINGS FIRST is a revolutionary guide to managing your time by learning how to balance your life. Traditional time management suggests that working harder, smarter and faster will help you gain control of your life, and that increased control will bring peace and fulfilment.','Paperback','English','37641','Y','Reference books','Lent');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (1471131823,'Self Help','Seven Habits Of HighLy Effective People','',' R. Stephen Covey ','t is rightly said that habits make or break a man. If you want to know why you are not doing something right, sometimes all you need is to perform an analysis of your habits and consider altering them. Because sometimes it’s not about what you do, but more about how you do it! And that’s where your habits play a very important role.','Paperback','English','43466','Y','Reference books','Lent');
INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9381860572,'Management','The Go Getter: The Story That Tells You How To Be One','','Peter B Kyne ','','Paperback','English','41275','N','Reference books','Acquire');

INSERT INTO BOOK (ISBN,SUBJECT_AREA,TITLE,VOLUME,AUTHOR,DESCRIPTION,BINDING,LANGUAGE,EDITION,AVAILABILITY,BOOK_TYPE,STATUS_TYPE) VALUES (9780241257494,'Psychology','Teach Your Child How To Think','','Edward de Bono','Edward de Bono, one of the world leading authorities on creative thinking, shows how parents can raise happy, confident and self-assured children through his simple tips, tricks and exercises that you can do with your child.','Paperback','English','42334','Y','Reference books','Lent');

