
CREATE OR REPLACE VIEW VW_BORROWED_BOOKS AS
SELECT B.BOOK_ID, A.SUBJECT_AREA, A.ISBN, A.TITLE, A.AUTHOR, A.BINDING,
A.LANGUAGE, A.AVAILABILITY, B.STATUS, B.M_SSN, B.ISSUED_BY, B.ISSUE_DATE
FROM BOOK A, COPY C, BORROW B, MEMBER M
WHERE
B.RETURN_DATE is null
and B.BOOK_ID = C.BOOK_ID
and C.ISBN = A.ISBN
and B.M_SSN = M.SSN;